### ISSUE TITLE
Directory Restructuring

### ISSUE THREAD

**Issue by adamblake** [gikeymarcia/Collector#111]
Change the structure of Collector to allow for multiple experiments with one set of core files. Will require modifying both the directory structure and pathing.
Proposed structure:
* Code/
* Tools
* Experiments/
    * Common/
        * Ineligibility
        * TrialTypes/
        * Images/
        * Audio/
        * Video/
        * common_settings.ini
    * Experiment1/
        * Ineligibility/
        * Stimuli/
        * Procedure/
        * Conditions.php
        * basic_settings.ini
        * advanced_settings.ini
    * Experiment2/
        * Ineligibility/
        * Stimuli/
        * Procedure/
        * Conditions.php
        * basic_settings.ini
        * advanced_settings.ini
* Data/
    * Experiment1-Data/
    * Experiment2-Data/

**Comment by TysonKerr** [comment]
Looks good. When we have final questions/basicinfo as csvs, that will go along-side the conditions file. But shouldn't eligibility be in the common section of experiment/ ? If you are re-using the paintings stimuli, you would want to exclude the people who have already studied them. Also, I think we talked about it before, but we should change Eligibility/ to Ineligibility/, since it is a list of people who are not allowed to participate.

In each of the media type folders, we should put a small txt file explaining what files they can use, and possible why they would use one file type vs another. For example, in video, we should say that mp4, ogg, and webm are supported, but webm and ogg might not be as supported as mp4 files.

Looking at settings.php, here is how we might break it up:

* common:

 * which experiment to use
 * password
 * email address
* experiment/basic:

 *  `$experimentName`
 *   `$doDemographics`
 *   `$doInstructions`
 *   `$doFinalQuestions` - since we have `$doDemographics`
 *   `$showConditionSelector`
 *   `$verification`
 *   `$checkElig`
* experiment/advanced

 *   other index.php settings, like `$useConditionNames`
 *   debugging tools
 *   `$loginCounterName`
 *   other eligibility settings
 *   `$lenientCriteria`

I think the Welcome page messages probably need to move to another file. Perhaps something similar to how we do Experiment/instructions.php? Or, rather than having the entire phrases as settings, we can just have `$experimentDuration` and `$mturkMode`, which will change the prompt for "Participant ID" or "MTurk ID".

**Comment by adamblake** [comment]
Good point about ineligibility. I forgot to add that folder to the Common directory as well (exclude from ALL experiments, such as for bad workers). Fixed it up above

Thanks for the settings suggestions -- looks good

**Comment by TysonKerr** [comment]
Actually, perhaps instead of a setting for experiment name, we can just use the folder name? So, if you are in the experiment contained in the folder "Interleaving Math Problems", then that should also work as your experiment name.

**Comment by gikeymarcia** [comment]
1. I thought the idea was to move /TrialTypes/ to root
2. Before beginning this work pull the newest `dev` because I renamed `/Eligibility/` to `/Ineligible/`

**Comment by TysonKerr** [comment]
1. Functionally, this is the same, since the trial types folder is in the common/ folder of experiments.

**Comment by gikeymarcia** [comment]
@TysonKerr sounds good. Somehow we've managed to go back to my initial suggestion of using `/Experiment/` as the home for all trial types.

As an addendum, are we going to keep a copy of all trial types in `/Code/`? The benefit here is that if someone completely breaks a trial type inside of `/Experiment/Common/TrialTypes/` they can delete the trial type and the program will default back to the initial state of that given trial type.

**Comment by TysonKerr** [comment]
I think the main reason I wanted a separate folder for trial types is so that there is one very clear non-programmer area, and then trial types would be a sort of in-between point between experiment and code. But, having a common area already helps separate these areas out. So, if people are going to be copying and pasting an update in, how should we expect people to do this? Should they copy in their individual experiment folders into the Experiment/ folder? Or, are they copying over the entire Experiment/ folder? Or, should they be copying the new Code/ into their folder? I think we should tell people to copy over the individual experiments, so that we can keep updating common, although they will also need to copy over any new trial types they have made, and they will have to navigate from the root a bit.

Having a copy of all the trial types seems a bit wasteful, but simple enough to implement. I can make a function which just copies the specific trial type directory from Code/ to Common/, which we can use in a Tools/clean.php function or something like that. And, the getTrialTypeFiles() function could be easily upgraded to search the Code/ folder if the target trial type isnt found, and if its found in Code/, run the transfer function from above.

I could probably save a little bit of space by somehow encoding the current trial types folder into a single file, and if something needs to be rewritten, just rewrite it from that single file. We would have to reconvert the trial types folder into its compressed state every time we make a change or add a new type, though.

**Comment by gikeymarcia** [comment]
hmmm maybe for now we only have one location `Experiment/Common/TrialTypes/` and kick the flexibility and restore stuff down the road to Collector2.1

**Comment by gikeymarcia** [comment]
we should rename `Config.ini` to `Settings.ini`

**Comment by adamblake** [comment]
Took a hiatus and it appears this got taken care of in a different direction, right? Multiple Experiments seems to cover it nicely

**Comment by TysonKerr** [comment]
Multiple-experiments lets you log in and complete multiple experiments, but getdata doesnt really work well. Also, I havent split the config fiels into basic and advanced, and the way I combine the common config and the experiment config is pretty messy. But, hopefully, this branch can get cleaned up and pushed to dev in a few weeks.

**Comment by gikeymarcia** [comment]
Multiple-experiments now works in JITexp
