### ISSUE TITLE
make CSS more targeted to elements

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#50]

**Comment by adamblake** [comment]
I am working on this presently. Specifically converting the CSS and HTML to have very few base styles. I'll put up some work on a feature branch tonght.

**Comment by adamblake** [comment]
I'll do some base edits like moving all of the form CSS to specific classes, but after that I'll move all of the inline styles to the stylesheet.

**Comment by gikeymarcia** [comment]
Looks like something you did created a new `Dev` branch. Change your commit c20242382acc5359e2bb88a686eebb3302c82e87 so it goes into `dev` (all lowercase) then I'll delete the `Dev` branch.

**Comment by gikeymarcia** [comment]
@adamblake , could you do a careful merge of the current dev into this branch so we can merge your changes in. I let this sit here far too long because I was not yet in the mode of having a dev branch that we can be messing with actively and I was more thinking that everything needed the same level of review as was previously done with all commits to master.

@TysonKerr any feedback you have on the topic of this css overhaul is welcome in this thread. No one does more regular css editing to Collector than you and it would be helpful to know where you stand on the current pull request.

**Comment by TysonKerr** [comment]
One thing that might be helpful is to attach the css of a specific trial type to that type's folder, rather than leaving it in the global CSS file. When I show people how to make new trial types, I usually do something like copy/paste the study trial type, and then change the text color, and I think it would be easier to explain where a lot of the styles are coming from if it was in that same folder. Then, if people want to modify some of these default styles on their copied trial types, they just need to edit the relevant styles in that folder, rather than hunting down the original css rules, copying them with different names, and reassigning the class names in their trial type.

However, I have made lots of different versions of the likert trial type, and I remember when I tried making it without knowing much css, it was quite puzzling when I didn't know that inline elements couldn't be assigned a width, or that the little spaces in between elements would add white space so that 10 elements with 10% width wouldn't fit together on one line. Maybe it would be helpful to make a CreateLikert() function, which you can give it a set of values and value descriptions, and it will automatically echo out all the html and css needed to make that likert scale. In that case, leaving the likert css in the global file would be great, because if you decide you want a different likert style, you can edit it there, and then this can be used if we want to add likert scales to demographics or final questions, as well as any other trial types that need a likert scale.

**Comment by adamblake** [comment]
Hmmm. Up to you guys entirely on breaking the css out like that. Seems like it might be a good idea, but at the same time it would lead to some messy HTML (could be fixed by using a templating system but that seems like overkill for this!)

Basically---up to you guys if you want to break the CSS out into different files, I don't really have a preference on that :D 

I do think that that seems like its own issue though, so if no one has any other concerns with this, I'll merge it into the dev branch

**Comment by gikeymarcia** [comment]
Merge away. We can all mess with it once it is in the dev branch but I think this is a big step forward from where we're at right now.
