### ISSUE TITLE
Final questions needs to be rethought

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#52]

**Comment by adamblake** [comment]
In my opinion (and I think yours as well, Mikey) there is no real conceptual difference between these questions and any other trials. Here's an idea we might want to pursue/refine:

Create a new trial type for each supported form element (fq-radio, fq-checkbox, etc.)
Allow users to use the shuffle column as a grouping column so that the questions are grouped onto predetermined pages
If no grouping is used, present all as one form

**Comment by gikeymarcia** [comment]
I think this is a good idea. Right now they're are weird old code that needs to be brought in line with the rest of Collector

**Comment by TysonKerr** [comment]
In general, I think a good way to allow this sort of Combined Trial would be if we made most of the work of trial.php, such as setting up aliases, checking for files to include, and setting up timing, inside a function, like createTrial(). Then, if a trial type can indicate that the next trial should also be included, we can just increment $currentPos, and run createTrial(), which should create a new scope so that all of our aliases don't interfere.

One problem that might come up is the html inputs wouldn't have unique names, and everything would just be called "Response". Perhaps we could wrap each trial type in its own form, but when it comes time to submit, cancel the default submission, and create a new form where we merge all the trials together. We can add a prefix based on the trial number, and then have trial.php figure out how to group different sets of data to send to scoring.php. This would make post trials a little weird, though.  Also, depending on the trial types, people are using, javascript might start to target the wrong elements. And there is the issue that there would be multiple submit buttons, as well as several elements with the same ID.

I actually made a Combined column which allowed multiple trial types to be presented together in a verrry old version of the Collector. One issue I ran into was when you shuffled these columns, sometimes you messed up the combining.  For example, if you had twelve questions, and you wanted to present blocks of 4, but you wanted to randomize the order, you might set the combined column to 1,1,1,1, 2,2,2,2, 3,3,3,3. But if you shuffled that, it might become 1,3,2,1,3,2,2,1.... which wouldn't group things any more. Of course, you can just be careful, and not shuffle these rows in the procedure file, and use the stimuli file to shuffle if you need to, or use the advanced shuffles to target the columns besides the Combine column, but it would just need to be something we explain to people, since this seemed to be an issue that wasn't intuitive to many people.


All that being said, it might be better to just use a survey trial type, which looks up a csv file full of questions, sort of like how image trial types look up an image in the Experiment/ folder. Then, people can just have a single trial, which looks up the finalQuestions.csv file, and writes everything out on the page. I have a basic type, which currently only supports Yes/no questions, but it would be pretty easy to add more types of questions, and then it already has some support for custom score, and naming each question (so that if you have a question like "What is your favorite color?", you can use a "Name" question in the survey file with an entry like "Favorite_Color", and that will make the output get stored into a column called "Favorite_Color", rather than just "Response1".

**Comment by gikeymarcia** [comment]
Agree with Tyson. Maybe this should be a new issue.
