### ISSUE TITLE
StudyPic not focusing on button

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#70]
Made a trial that has a min and max time and the submit button is not getting the focus.

For non-input trials we should focus on the submit button if it is visible.  This might not be a bug but this functionality should be in so people can submit the trial by pressing enter

**Comment by adamblake** [comment]
Currently, I believe that the Javascript looks for and focuses the first input box. I think that we might be better off if we add "autofocus" properties (HTML5) to the tags we want to get first focus and then use something like Modernizr to provide a JS fallback for browsers that don't support it.

**Comment by TysonKerr** [comment]
Adding a feature detection library would also be helpful for people that want to use html5 audio/video elements. We could add an option in Settings.php to check for this, so that people can be sure that their participants can actually do the experiment.

Currently, the focus is just made on the first :input element that Jquery finds, but this only happens at the page load, before the min time has been reached. But, it would be simple to just add another line to the min time callback function, which detects if there is no focus, and if so, focus on the first visible :input.

**Comment by gikeymarcia** [comment]
HTML5 is in by adding autofocus property to the button but it won't work in old browsers

**Comment by gikeymarcia** [comment]
For now I'll mark this as closed because it's fixed enough to be low priority.
