### ISSUE TITLE
Min Time function

### ISSUE THREAD

**Issue by veronicayan** [gikeymarcia/Collector#71]
Trying to set Min Time = 2, and Max Time/Timing = user. MCPic trial functions as if it's just user-timed, not forcing participant to view the image for a minimum of 2 seconds. 

(for www.cogfog.com/VY/SnakesLOC6/)

**Comment by gikeymarcia** [comment]
I think it is agreed that the default functionality in this case should be that users are allowed to click buttons before `Min Time` is reached and when we reach `Min Time` if a selection had been made then that selection should be submitted to the server.  If `Min Time` is reached before the selection is made then upon selection the choice will be submitted to the server.

**Comment by adamblake** [comment]
I didn't realize that this is what you wanted the default to be. I thought that the point of the minimum was to make sure that participants were focusing on the stim for some set period before they were allowed to do anything... I think that I updated those buttons to be unclickable until the timer runs out in other trials, and I must have missed the MCPic trial.

**Comment by TysonKerr** [comment]
Well, for test and freerecall, people can type before the min time ends, they just can't submit anything.  McPic is just a weird case, because unlike those cases, the input and the submit are tied together, so you can't disable the submit without also preventing input. It makes sense for other trials to disable the submit button and make it unclickable, but with McPic, min time should just prevent the submitting behavior of making a choice. when min time is reached, the submit functionality is restored, and if an input has already been made, then the trial can submit automatically at that point.

**Comment by gikeymarcia** [comment]
Yeah, I'm in agreement with Tyson for the MCpic trials. Adam, do you an alternate way you'd think it should function?

**Comment by adamblake** [comment]
Just from a decision making and studying standpoint I am thinking that once you push the button you can mentally put aside the current task. Thus, minTime would be irrelevant for these people: they came to their decision beforehand and extra time will have no effect on studying or deciding. By leaving the button disabled, you force the task to remain open and for them to at the minimum think about the answer they are going to give.

I think this would apply to every trial *except* for FreeRecall where the point would be to force them to continue to recall for a minimum amount of time. For all other trials, it makes more sense that people would want them to be thinking about the cue/answer for a minimum time before outputting and discarding it (even for Test, this makes sense in the spirit of a minTime, because even if they know the answer they should be forced to hold it in mind for the set minimum).

Just my $.02 !

**Comment by gikeymarcia** [comment]
@TysonKerr isn't this fixed by 1049b6b208c77d54ea3d4ad177dfd7856a95c508 ?

**Comment by TysonKerr** [comment]
Should be fixed! Hopefully...
